### PR TITLE
API for integration with other plugins

### PR DESCRIPTION
**Pull request by RyotaUshio**
Hi, thank you again for maintaining this awesome project.

Recently, I've been developing a new plugin for mathematical note taking.
In the development process, I realized that MathLinks is very powerful not only in rendering MathJax but also in dynamically updating link texts.
It would be great if other community plugins could utilize this power.

At first, I was directly editing the YAML frontmatter and adding `mathLink`/`mathLink-blocks` to do it. However, this is unsafe and degrades users' experience.

So, I would like to propose adding an API to MathLinks for integration with other plugins. 

I would truly appreciate it if you could approve this PR and include it in the next release, in which case my plugin will be able to provide really awesome experience to many Obsidian users who take mathematical notes. 
It will be beneficial for other plugin developers, too.

If you are interested in what can be done with this API, please check out the followings:

- repo: https://github.com/RyotaUshio/obsidian-math-booster
- docs (tentative): https://ryotaushio.github.io/obsidian-math-booster/

(Note that you have to clone the latest commit of the [add-api branch of my fork](https://github.com/RyotaUshio/obsidian-mathlinks/tree/add-api) and the [master branch of my plugin](https://github.com/RyotaUshio/obsidian-math-booster) if you want to try it.)

Let me explain the related codes that I've added. 

### [api.ts](https://github.com/RyotaUshio/obsidian-mathlinks/blob/add-api/src/api.ts)

```ts
export interface MathLinksMetadata {
    "mathLink"?: string;
    "mathLink-blocks"?: Record<string, string>
}

export type MathLinksMetadataSet = Record<string, MathLinksMetadata>; // {[path]: [metadata for the file], ...}

export class MathLinksAPIAccount {
    metadataSet: MathLinksMetadataSet;
    constructor(public plugin: MathLinks, public manifest: PluginManifest, public blockPrefix: string);
    update(path: string, newMetadata: MathLinksMetadata): void;
    get(path: string, blockID?: string): string | undefined;
    delete(path: string, which?: string): void;
    deleteAccount(): void;
}
```

- `MathLinksMetadata` is the same thing as `mathLink` and `mathLink-blocks` in the YAML frontmater.
- `MathLinksMetadataSet` is a dictionary whose key is a note path and the value is the corresponding `MathLinksMetadata` object.
- `MathLinksAPIAccount` is the interface through which another plugin can handle its `MathLinksMetadataSet` object. 
  - Each plugin that wants to use this API is given an account. 
  - Each account has access to its own `metadataSet` only. It cannot modify the user-defined `mathLink` field in the frontmatter, nor other user plugins' `metadataSet`.
  - It can update/delete `mathLinks`/`mathLink-blocks` metadata **in a programmatic manner without directly editing the YAML frontmatter**.

### [main.ts](https://github.com/RyotaUshio/obsidian-mathlinks/blob/add-api/src/main.ts)

```ts
export default class MathLinks extends Plugin {
    apiAccounts: MathLinksAPIAccount[];
    ...
    getAPIAccount(userPlugin: Plugin, blockPrefix: string = "^"): MathLinksAPIAccount;
}
```

If another plugin (`userPlugin`) wants to use the API, it calls the `getAPIAccount` method of `MathLinks`. It registers `userPlugin` as a user of MathLinks API and returns its account.
All the issued account are stored in `apiAccounts`.

### [tools.ts/getMathLink()](https://github.com/RyotaUshio/obsidian-mathlinks/blob/c6604379a63b4133b1b4854a423af8e47ae4552f/src/tools.ts#L122)

Importantly, the metadata registered by other plugins via the API is used, only if the frontmatter doesn't have `mathLink` (or `mathLink-blocks`).
Therefore, **adding the API will not cause any change if mathLinks already exist in the frontmatter**.
**User-defined (i.e. defined in the frontmatter) mathLinks always have the highest precedence.**

(As you can see in the code, the precedence among user plugins is determined by the order in which they are stored in `MathLinks.apiAccounts`. So it would be possible to allow users to change this precedence in the settings.)

### [settings.ts](https://github.com/RyotaUshio/obsidian-mathlinks/blob/c6604379a63b4133b1b4854a423af8e47ae4552f/src/settings.ts#L226)

In the MathLinks settings, users can choose whether to allow other plugins to use the API.

image

Thank you!

### CODE REVIEW

**Comment by RyotaUshio** [comment]
By the way, in my implementation, #31 can be done by passing a user's custom prefix to the `blockPrefix` parameter of [getMathLinkFromSubpath()](https://github.com/RyotaUshio/obsidian-mathlinks/blob/c6604379a63b4133b1b4854a423af8e47ae4552f/src/tools.ts#L142).

**Comment by zhaoshenzhai** [comment]
Really, really cool!

My understanding of APIs and how to work with them effectively is still very shallow, so I don't know whether the current implementation allows for the most flexibility etc. If you want to make any improvements (like exposing more features to the API), feel free to make more PRs!

> By the way, in my implementation, #31 can be (partially) addressed by passing a user's custom prefix to the `blockPrefix` parameter of [getMathLinkFromSubpath()](https://github.com/RyotaUshio/obsidian-mathlinks/blob/c6604379a63b4133b1b4854a423af8e47ae4552f/src/tools.ts#L142).

I will add an option to customize the `blockPrefix`, as well as an option to exclude the file name if a `subpath` is found (so that `name>^block` is turned into `block`; this will be disabled by default, but for my specific use case I only want `block` to be rendered.)

I will include this PR in a release today. Thank you again for your contributions :)

**Comment by zhaoshenzhai** [comment]
Oops I made the same mistake of closing instead of merging...

**Comment by RyotaUshio** [comment]
Thank you, I appreciate it so much. Also, congrats on the new release!

> My understanding of APIs and how to work with them effectively is still very shallow, so I don't know whether the current implementation allows for the most flexibility etc. If you want to make any improvements (like exposing more features to the API), feel free to make more PRs!

The next step would be distributing the MathLinks API as a npm package.
It will exclude the need for user plugins to manually declare the API interface (which is clearly suboptimal), like I'm currently doing in my project: 
https://github.com/RyotaUshio/obsidian-math-booster/blob/master/src/mathLinksAPI.ts

The Dataview API would be a nice reference for how we should do that.
https://blacksmithgu.github.io/obsidian-dataview/resources/develop-against-dataview/

To be honest, I'm pretty new to Typescript/Javascript so I'm not very sure about how this should go either for now. I will find time and keep on improving the API.

> I will add an option to customize the `blockPrefix`, as well as an option to exclude the file name if a `subpath` is found (so that `name>^block` is turned into `block`

That's awesome! 👍 It would be nice to include that option in the `getAPIAccount` too.

> for my specific use case I only want block to be rendered.

I feel the same!

**Comment by RyotaUshio** [comment]
[Callout Manager](https://github.com/eth-p/obsidian-callout-manager) is another example of an Obsidian plugin that has an API for integration with other plugins. 
I will look up Dataview and Callout Manager for the time being and figure out how we should package the MathLinks API.

**Pull request merged**
