### PR TITLE
Issue 4: Dataview support

### PR DESCRIPTION
**Pull request by zhaoshenzhai**

### CODE REVIEW

**Comment by joelatschool** [comment]
Thanks so much! This *nearly* works perfectly; the only issue I've found is that Dataview queries may replace the text of a link to a note with some other text. For example:
```dataview
LIST WITHOUT ID link(file.path, "test") FROM "Notes"
```
will create a list of links to every note in /Notes but where the text of each link is with the word "test", like the following: 
image

The problem is that this version of the plugin replaces that text with the `mathLink` if it's defined, no matter what. So this displays as
image

This isn't a big problem for me, because the only reason I use the `link(,)` feature is to get the mathLink to display in my vault. As such, this bug breaks my workaround:
image
but also fixes the thing it's working around:
image

However, it could still break other people's workflow, so it should probably be fixed before a release or if that isn't possible, there should be an option to turn the feature on and off. 

Thanks again!

**Comment by zhaoshenzhai** [comment]
Ahh, I see; I didn't know that dataview can replace the text of a link. If it leaves some trace that it does so, this should be an easy fix. I'll look into it.

**Comment by zhaoshenzhai** [comment]
Okay, I tried another method that hopefully should fix this. Could you please try downloading `main.js` (from the same `0.2.6` pre-release) again and see if it works?

**Comment by joelatschool** [comment]
Works perfectly in my vault, thanks so much!

**Pull request merged**
