### PR TITLE
[based on 0.4.2] Fix dynamic updates in reading mode & remove `targetDisplay` in `MathLinksRenderChild`

### PR DESCRIPTION
**Pull request by RyotaUshio**
I propose two options for resolving #35.

1. based on the previous release 0.4.1: #37 
2. based on the latest release 0.4.2: This PR

Please choose the one you prefer (if exists).

---

# Common modification

Both 1 & 2 have the following modification in common:

In `MathLinksRenderChild.update()`, `targetDisplay` should be replaced with `this.displayText` because the former is overwritten when `mathLink` is updated but the latter remains untouched.

Having `targetDisplay` seems to do little harm for mathLinks registered via the YAML frontmatter, but it is problematic for API mathLinks.

---

# Changes specific to this PR

- `MathLInksRenderChild` keeps both the original link element `this.containerEl` and the MathLinks element `this.mathLInkEl` in it as its properties.
- `addMathLink` is now `setMathLink`. The following code
```ts
    if (newElement) {
        targetEl.parentNode?.insertBefore(mathLinkEl, targetEl.nextSibling);
        mathLinkEl.classList.add("mathLink-internal-link");
        targetEl.classList.add("original-internal-link");
        targetEl.style.display = "none";
    }
```
at the last part of `addMathLink` has been moved to `MathLinksRenderChild`'s constructor because it is only used for reading mode.

### CODE REVIEW

**Comment by RyotaUshio** [comment]
`0.4.1` has no problem with dynamic updates, and `0.4.2` is the one that has.

I wasn't aware of the heading issue... I will take a look on it.

**Comment by zhaoshenzhai** [comment]
Oops, sorry, I meant `0.4.2`.

**Comment by RyotaUshio** [comment]
You mean the dynamic update is working on `0.4.2`? That's different from mine...

Here's a test on `0.4.2`:

https://github.com/zhaoshenzhai/obsidian-mathlinks/assets/72342591/605f8a05-d317-4533-baf4-86691ba1dfdf

**Comment by RyotaUshio** [comment]
The result was the same for the sandbox vault & MathLinks 0.4.2 installed via the community plugins list inside theObsidian app.

**Comment by zhaoshenzhai** [comment]
I tested it again and `0.4.2` really does seem to work for me. I'm on Obsidian `1.3.7` too.

https://github.com/zhaoshenzhai/obsidian-mathlinks/assets/47350090/5740d04e-9466-4067-a857-36b2c3446ef7

**Comment by zhaoshenzhai** [comment]
Here, I showcase the behaviour for `0.4.2` and the `fix-reading-mode` branch with and without `obsidian-math-booster`.

https://github.com/zhaoshenzhai/obsidian-mathlinks/assets/47350090/0b1b725d-2830-4350-9b1d-c978b291dcd3

**Comment by RyotaUshio** [comment]
>  it seems that obsidian-math-booster is the one causing the heading issue.

Wow, I'm so sorry for that... 
But I don't fully get it because I don't have the heading issue even if I'm enabling Math Booster. 
How did you install it? I'm asking because I renamed my plugin "Math Booster" (without" Obsidian") when releasing 0.3.0, but there is **Obsidian** Math Booster ver. 0.3.0 in the plugin list.

**Comment by zhaoshenzhai** [comment]
Oops what did I do. I was trying to resolve a conflict on GitHub and something happened... one second.

**Comment by RyotaUshio** [comment]
> everything worked in the fix-reading-mode branch! (dynamic updating, and there is no header issue).

Oh that's so nice to hear! I'm now really relieved.

**Comment by zhaoshenzhai** [comment]
> Oops what did I do. I was trying to resolve a conflict on GitHub and something happened... one second.

Nevermind, everythings ok. Should I release this fix as `0.4.3` now? or is there something else you wanted to add/fix (everythings ok on my part)

**Comment by RyotaUshio** [comment]
I don't have anything to add for now! So please go ahead. Thank you again for the quick responses.

**Comment by RyotaUshio** [comment]
Oh, just in case, please don't forget to update the npm package.

**Comment by zhaoshenzhai** [comment]
> Oh, just in case, please don't forget to update the npm package too.

Will do.

**Pull request merged**
