### PR TITLE
Resolve #55: render MathJax in the outline

### LINKED ISSUE #55: Render LaTeX in the outliner
I think it would be a good idea to make headers containing LaTeX expressions display correctly in the outliner.

I have notes with examples of solving maths problems, and I often put the problems themselves in the headers. Now it looks unreadable in the outliner, and I would be very happy if this plugin could fix this situation.

image

### PR DESCRIPTION
**Pull request by RyotaUshio**
This PR adds the feature to render MathJax inside the core [Outline](https://help.obsidian.md/Plugins/Outline) view.

image

> [!WARNING]
> You will have to run the command "Reload app without saving" to see the effect.

This is achieved by tweaking the (unexposed) outline view's prototype using https://github.com/pjeby/monkey-around, a helper library that is used by many Obsidian plugins.

Acknowledgment: I was inspired by the following plugins.

- Hover Editor (https://github.com/nothingislost/obsidian-hover-editor)
- MAKE.md (https://github.com/Make-md/makemd)
- Better Search Views (https://github.com/ivan-lednev/better-search-views)
- Floating Search (https://github.com/Quorafind/Obsidian-Float-Search)
- AidenLx's Folder Note (https://github.com/aidenlx/alx-folder-note)

### CODE REVIEW

**Comment by RyotaUshio** [comment]
Confirmed that both of the core Outline plugin's two features that are mentioned in the [help page](https://help.obsidian.md/Plugins/Outline) work without problems:

1. _"To navigate to that section in the note, click on the heading in the outline."_
2. _"To rearrange sections in the note, click and drag the heading within the outline."_

**Comment by RyotaUshio** [comment]
Should this be `0.4.8` or `0.5.0`?

**Comment by RyotaUshio** [comment]
I think it's ready. Should this be `0.4.8` or `0.5.0`?

**Comment by zhaoshenzhai** [comment]
Brilliant work as always!

> I think it's ready. Should this be `0.4.8` or `0.5.0`?

In retrospect, the previous update should have been `0.5.0` as it completely overhauled the API. Maybe we can release this as `0.5.0` instead and reference the previous update as the 'major change'? If this is okay with you, feel free to release it anytime.

**Comment by RyotaUshio** [comment]
Thanks!

Technically, Semantic Versioning seems not to define any particular rules for major version zero (`0.y.z`).
https://semver.org/#spec-item-4

But if we respect the rules stated for version >= 1.0.0, you are right, the previous release should have been `0.5.0`.
https://semver.org/#spec-item-7

> Minor version Y (x.Y.z | x > 0) MUST be incremented if new, backward compatible functionality is introduced to the public API. It MUST be incremented if any public API functionality is marked as deprecated.

Sorry I didn't fully understand it. I thought API changes are not enough to bump up the minor version (`y`), but I was wrong. Plus, there was also a new feature for normal users (i.e. source mode support) so it was surely enough to be `0.5.0`.

But modyfing an existing release is not allowed, so I will release this as `0.5.0` and reference the previous update in the release note as you suggest.

**Comment by RyotaUshio** [comment]
Can you update README with a release note for 0.5.0 and the description for this new feature when you have time?
(Sorry I pushed d1f2b466e9ab ("release `0.5.0`") without updating README by mistake, so I reverted it.)

**Comment by zhaoshenzhai** [comment]
> Can you update README with a release note for 0.5.0 and the description for this new feature, and then make a release when you have time?

For sure, I'll do it now.

**Pull request merged**
