### PR TITLE
Publishing the API as a npm package

### PR DESCRIPTION
**Pull request by RyotaUshio**
Context: https://github.com/zhaoshenzhai/obsidian-mathlinks/pull/32#issuecomment-1666950928

I've started working on publishing the API as a npm package.

There are several community plugins that are providing APIs:

- Dataview: https://blacksmithgu.github.io/obsidian-dataview/resources/develop-against-dataview/
- Folder Note Core: https://github.com/aidenlx/folder-note-core/tree/master
- Callout Manager: https://github.com/eth-p/obsidian-callout-manager/blob/master/api/README.md
- Metadata Menu: https://mdelobelle.github.io/metadatamenu/api/

They are nice references to look up to (but Metadata Menu seems not to provide a npm-installable package).

Following them (especially Dataview and Folder Note Core), I prepared some files needed to npm publication (bfc8b76baec52404).

Now, probably the only job I need to do is running `npm run lib` (`lib` was added in the `script` field of [package.json](https://github.com/RyotaUshio/obsidian-mathlinks/blob/bfc8b76baec5240408552a662fd87605a6a577cd/package.json#L13)). 
But this gives a lot of errors, which are the same as those appear when running `npm run build` (https://github.com/zhaoshenzhai/obsidian-mathlinks/pull/30#discussion_r1285252309).
So I perhaps need to fix these errors first. 

(You don't need to merge this PR right now, I create it to let you know the current situation.)

### CODE REVIEW

**Comment by RyotaUshio** [comment]
Could you experimentally publish it to the npm registry?

1. First, run `npm run lib` to generate files under the `lib` directory.
2. Next, run `run publish --access public`. You will need a npm user account to do this.

Then, I will check if things are working properly.

**Comment by RyotaUshio** [comment]
I **locally** tested `npm install path/to/obsidian-mathlinks` and it seems to be working well!

After you confirm there's no problem with the code, you can publish the API as a npm package (which is cool!).

1. First, run `npm run lib` to generate files to distribute under the `lib` directory.
2. Next, run `npm publish` with the option you like (unscoped public/scoped public). You will need a npm user account to do this.

**Comment by RyotaUshio** [comment]
Here are some screenshots from the source code of my plugin. So cool!

image


image

**Comment by zhaoshenzhai** [comment]
Hi! Thank you so much for all your work, I really do appreciate it.

A quick test in my vault shows that everything is working! There are some parts of your code that I do not understand (especially in `index.ts`, `api.ts`, and `type.d.ts`), but thats just because of my lack of typescript knowledge and experience.

I do have some other comments though:
* Regarding canvases (mentioned [here](https://github.com/zhaoshenzhai/obsidian-mathlinks/pull/34)): The `isValid()` check should always accept canvases as it is not a 'note' itself, but rather collects multiple notes together. I will uncomment your third solution:
  ```ts
  if (fileName.endsWith(".canvas")) return true;
  ```
  Individual notes within canvases should respect whether it is excluded or not (this is currently working).
* Going over my old code, I realised that excluded files still rendered in live-preview. I have fixed it in `preview.ts` as
  ```ts
  if (leaf.view instanceof MarkdownView && isValid(plugin, leaf.view.file.name)) { ... }
  ```
* Apologies if I misunderstood, but shouldn't the `deleteAccount` function in `api.ts` be in `index.ts`? That seems like a more appropriate place for it to be.

**Comment by RyotaUshio** [comment]
> There are some parts of your code that I do not understand (especially in index.ts, api.ts, and type.d.ts), but thats just because of my lack of typescript knowledge and experience.

Feel free to ask anything if you want to know. 
Although I paid special attention when I wrote all these codes, I'm not an experienced typescript/javascript programmer (in fact, I started them just a month ago to make my Obsidian plugins) so how I did it might not be the best one.

> canvases as it is not a 'note' itself, but rather collects multiple notes together.

Oh I see, that makes sense! Thanks for elaborating.

> shouldn't the deleteAccount function in api.ts be in index.ts?

Do you mean, it currently lives inside the MathLinksAPIAccount class as a method, 
```ts
// api.ts
export class MathLinksAPIAccount {
    ...
    deleteAccount(): void {
        let index = this.plugin.apiAccounts.findIndex(
            (account) => account.manifest.id == this.manifest.id
        );
        this.plugin.apiAccounts.splice(index, 1);
    }
}
```

..., but it should be placed in index.ts as a utility function so that `getAPIAccount` and `deleteAPIAccount` make a pair, like this one?

```ts
// index.ts
export const deleteAPIAccount = <UserPlugin extends Plugin>(userPlugin: UserPlugin): void => {
    let accounts = userPlugin.app.plugins.plugins.mathlinks?.apiAccounts;
    if (accounts) {
        let index = accounts.findIndex(
            (account) => account.manifest.id == userPlugin.manifest.id
        );
        accounts.splice(index, 1);
    }
}
```

Indeed, it can make a much sense than  the current interface.

**Comment by RyotaUshio** [comment]
As for the `deleteAccount` thing, there is another option. 

Currently, a user plugin must call `deleteAccount()` when being unloaded, like this:

https://github.com/RyotaUshio/obsidian-math-booster/blob/b2fe940e561cd592cd504c6d95470b6d9e9d3320/src/main.ts#L187

If it forgets this, the mathLinks registered by the user plugin remain even after the user plugin is disabled, which is not desirable.

But it might be unsafe to trust user plugins about this kind of management. 
So alternatively, we can make MathLinks itself constantly check which user plugin is enabled, and delete the account of an disabled plugin, if exists.

But yeah, it might be enough to write API documentation and make it clear that a user plugin must call `deleteAccount`.

**Comment by RyotaUshio** [comment]
Hi, let me explain the changes that I made since your last comment.

## Moved `deleteAccount` from api.ts (inside `MathLinksAPIAccount`) to index.ts

... and renamed it as `deleteAPIAccount` so that it matches with `getAPIAccount`.
As you pointed out, this makes more sense than the previous version, I feel.]

## Dynamic update of displayed text when MathLinks metadata (`mathLink`/`mathLink-blocks`) are changed via API

For example:
image

The upper-left pane is Live Preview, and the lower-left is reading mode. 

Now, I enable a user plugin. A new API account is created for this plugin.

image

Let's confirm it; yeah, it seems to be working well.

image

Now I run this:
```js
api.update(
    "Untitled.md", 
    {"mathLink-blocks": 
        {"my-id": "$\\int g \\, d \\mu$"}
    }
)
```
You can see the new `mathLink-blocks` metadata has been immediately reflected, both in live preview and reading mode:

image

Next, let's see what happens when disabling the user plugin.

image

The `mathLink-blocks` metadata registered by the API user is deleted, and as desired, the displayed text immediately reacts to it (i.e. it returns to "^my-id").

image


To accomplish this, I added the custom event on the `app.metadataCache`:
https://github.com/RyotaUshio/obsidian-mathlinks/blob/d9b48401855cc1dab46b9d19bfa027e451eaa514/src/type.d.ts#L33-L48

When the metadata is updated/deleted by an API user, or an account is deleted, the [informChange()](https://github.com/RyotaUshio/obsidian-mathlinks/blob/d9b48401855cc1dab46b9dZ19bfa027e451eaa514/src/api.ts#L82-L95) function is called.

- This triggers an appropriate event ( "mathlinks:updated" or "mathlinks:account-deleted", depending on what actually happened) so that the reading mode can [react to it](https://github.com/RyotaUshio/obsidian-mathlinks/blob/d9b48401855cc1dab46b9d19bfa027e451eaa514/src/main.ts#L19-L39), and 
- also calls `dispatch()` method of all the `EditorView` objects that are currently working so that live preview can be updated accordingly.

**Comment by zhaoshenzhai** [comment]
Hi, this looks great! Dynamic updating has always been an issue for me (I had to reload the page to update its mathlinks) and your implementation of the two events should fix it. Thanks for this :)

I don't think I'll be able to review your code properly though, as the next semester starts in a few weeks and I need to prepare for it. When I have time I'll learn the basics of typescript and give some more feedback, but for now let me know when this api is mature enough so I'll merge this pr, and publish it so that you can use it in your plugin as well.

**Comment by zhaoshenzhai** [comment]
> But it might be unsafe to trust user plugins about this kind of management. So alternatively, we can make MathLinks itself constantly check which user plugin is enabled, and delete the account of an disabled plugin, if exists.
> 
> But yeah, it might be enough to write API documentation and make it clear that a user plugin must call `deleteAccount`.

As far as I know I think its standard to ask for plugins to manage its cleanup process, so writing this is the documentation (which reminds me, I need to write a proper documentation...) should suffice.

**Comment by RyotaUshio** [comment]
> Dynamic updating has always been an issue for me

Currently dynamic updating is only available for API users, but probably it can be implemented similarly for the YAML frontmatter. I will give it a try tomorrow.

Thank you so much for sparing your time when you're busy. I also appreciate your consideration for my plugin.
I think almost everything is done, so tomorrow I will check things are working well, and let you know if it's OK.

As for the API docs, I can write the first draft if you want me to do. You can modify it as you like.

**Comment by RyotaUshio** [comment]
Hi @zhaoshenzhai, I rewrote the code for dynamic updates of reading mode.

The previous version, I was doing something like this:
```ts
// in MathLinks.onload()

        // Markdown Post Processor for reading view
        this.registerMarkdownPostProcessor((element, context) => {
            if (isValid(this, context.sourcePath)) {
                generateMathLinks(this, element, context.sourcePath);

                // dynamically update the displayed text
                // 1. when user updates the YAML frontmatter
                this.registerEvent(this.app.metadataCache.on("changed", (file) => {
                    if (file.path == context.sourcePath) {
                        generateMathLinks(this, element, context.sourcePath);
                    }
                }));

                // 2. when an API user updates its metadata
                this.registerEvent(this.app.metadataCache.on("mathlinks:updated", (apiAccount, path) => {
                    if (path == context.sourcePath) {
                        generateMathLinks(this, element, context.sourcePath);
                    }
                }));

                // 3. when an API account is deleted
                this.registerEvent(this.app.metadataCache.on("mathlinks:account-deleted", (apiAccount) => {
                    generateMathLinks(this, element, context.sourcePath);
                }));
            }
        });
```

I found two big failures in this approach (sorry...), which I addressed in the latest commit.

1: 
If a note is in reading mode when Obsidian starts up, so many duplicate mathLinks are rendered.
I know, it's hard to understand the situation with my poor explanation... Let me illustrate by an example.

This note looks nice :
image

But if you reopen the app, it breaks (look at the link "Dominated convergence theorem"):
image

Inspection:
image


I haven't completely understand this phenomenon, but the most likely explanation would be:
1. `app.metadataCache` is updated for **multiple times** at startup, each of which triggers the `changed` event, which in turn triggers the `mathlinks:updated` event through the user plugin's code
2. Each event calls the `generateMathLinks` function, but these calls happen so rapidly that the following snippet (seemingly intending to replace the old mathLink) doesn't work as expected;
```ts
// generateMathLinks()
        if (targetEl.classList.contains("mathLink-internal-link")) {
            targetEl.remove();
            ...
        }
```

After carefully inspecting the code, I thought the most straightforward solution would be rewriting the `generateMathLinks` function a little bit using `MarkdownRenderChild`. (Currently, this is the officially documented way of making a `MarkdownPostProcessor`; see the [docs](https://docs.obsidian.md/Plugins/Editor/Markdown+post+processing) for details).

As a result, there is a new `MathLinksRenderChild` class in `links.ts`: https://github.com/RyotaUshio/obsidian-mathlinks/blob/2973bc0aeec807bc330e36d4e602b0483dcac3ec/src/links.ts#L7-L53

Since the event handling code has moved to inside this class's `onload()` method, `main.ts` now looks like before:
https://github.com/RyotaUshio/obsidian-mathlinks/blob/4d08cc346cd8206fc816d311cf59cb5cae2aebf5/src/main.ts#L16-L21

2: The second failure is a more fundamental one, I'm sorry for almost introducing this bug...

When the metadata of `fileA` is updated, it is not `fileA` itself that has to update the mathLinks in it. It's `fileB` that has a link to `fileA`. In other words, `fileA`'s backlinks.

So, the previous code was terribly wrong:
```ts
                this.registerEvent(this.app.metadataCache.on("changed", (file) => {
                    if (file.path == context.sourcePath) {
                        generateMathLinks(this, element, context.sourcePath);
                    }
                }));
```

Instead, it should be:
```ts
       this.plugin.registerEvent(this.plugin.app.metadataCache.on("changed", (changedFile) => {
            if (!this.targetFile || this.targetFile == changedFile) {
                this.update();
            }
        }));
```
Here, `this` is the `MathLinksRenderChild` object that I mentioned above, and `this.targetFile` is the file the link goes to. In other words, it's `fileA` in this case.

After these modifications, it seems to be all fine now!

image

**Comment by RyotaUshio** [comment]
Hi @zhaoshenzhai, I rewrote the code for dynamic updates of reading mode.

The previous version, I was doing something like this:
```ts
// in MathLinks.onload()

        // Markdown Post Processor for reading view
        this.registerMarkdownPostProcessor((element, context) => {
            if (isValid(this, context.sourcePath)) {
                generateMathLinks(this, element, context.sourcePath);

                // dynamically update the displayed text
                // 1. when user updates the YAML frontmatter
                this.registerEvent(this.app.metadataCache.on("changed", (file) => {
                    if (file.path == context.sourcePath) {
                        generateMathLinks(this, element, context.sourcePath);
                    }
                }));

                // 2. when an API user updates its metadata
                this.registerEvent(this.app.metadataCache.on("mathlinks:updated", (apiAccount, path) => {
                    if (path == context.sourcePath) {
                        generateMathLinks(this, element, context.sourcePath);
                    }
                }));

                // 3. when an API account is deleted
                this.registerEvent(this.app.metadataCache.on("mathlinks:account-deleted", (apiAccount) => {
                    generateMathLinks(this, element, context.sourcePath);
                }));
            }
        });
```

I found two big failures in this approach (sorry...), which I addressed in the latest commit.

1: 
If a note is in reading mode when Obsidian starts up, so many duplicate mathLinks are rendered.
I know, it's hard to understand the situation with my poor explanation... Let me illustrate by an example.

This note looks nice :
image

But if you reopen the app, it breaks (look at the link "Dominated convergence theorem"):
image

Inspection:
image


I haven't completely understand this phenomenon, but the most likely explanation would be:
1. `app.metadataCache` is updated for **multiple times** at startup, each of which triggers the `changed` event, which in turn triggers the `mathlinks:updated` event through the user plugin's code
2. Each event calls the `generateMathLinks` function, but these calls happen so rapidly that the following snippet (seemingly intending to replace the old mathLink) doesn't work as expected;
```ts
// generateMathLinks()
        if (targetEl.classList.contains("mathLink-internal-link")) {
            targetEl.remove();
            ...
        }
```

After carefully inspecting the code, I thought the most straightforward solution would be rewriting the `generateMathLinks` function a little bit using `MarkdownRenderChild`. (Currently, this is the officially documented way of making a `MarkdownPostProcessor`; see the [docs](https://docs.obsidian.md/Plugins/Editor/Markdown+post+processing) for details).

As a result, there is a new `MathLinksRenderChild` class in `links.ts`: https://github.com/RyotaUshio/obsidian-mathlinks/blob/2973bc0aeec807bc330e36d4e602b0483dcac3ec/src/links.ts#L7-L53

Since the event handling code has moved to inside this class's `onload()` method, `main.ts` now looks like before:
https://github.com/RyotaUshio/obsidian-mathlinks/blob/4d08cc346cd8206fc816d311cf59cb5cae2aebf5/src/main.ts#L16-L21

2: The second failure is a more fundamental one, I'm sorry for almost introducing this bug...

When the metadata of `fileA` is updated, it is not `fileA` itself that has to update the mathLinks in it. It's `fileB` that has a link to `fileA`. In other words, `fileA`'s backlinks.

So, the previous code was terribly wrong:
```ts
                this.registerEvent(this.app.metadataCache.on("changed", (file) => {
                    if (file.path == context.sourcePath) {
                        generateMathLinks(this, element, context.sourcePath);
                    }
                }));
```

Instead, it should be:
```ts
       this.plugin.registerEvent(this.plugin.app.metadataCache.on("changed", (changedFile) => {
            if (!this.targetFile || this.targetFile == changedFile) {
                this.update();
            }
        }));
```
Here, `this` is the `MathLinksRenderChild` object that I mentioned above, and `this.targetFile` is the file the link goes to. In other words, it's `fileA` in this case.

After these modifications, it seems to be all fine now!

image

**Comment by RyotaUshio** [comment]
Let me show you some demonstlation of dynamic updates, including the case of YAML frontmatter.

### Live preview

Screen Recording 2023-08-13 at 23 24 36


[Imgur](https://i.imgur.com/4tuDAst.gifv)

### Reading mode

Screen Recording 2023-08-14 at 0 15 25

**Comment by RyotaUshio** [comment]
I think now the API is mature enough to be released. 
If you are fine with it, could you merge this PR and publish it to the npm registry?

Also, I appreciate it if you could include this in the next release so that the users of my plugin can enjoy the new features.
(Of course, I don't mean to rush you if you have something that you want to include in it other than this API update.)

**Comment by RyotaUshio** [comment]
Oh, I forgot to mention:

- Now, there is no `mathLink-internal-link`/`original-internal-link` classes. I think they are no more needed under the current implementation, but let me know if I'm missing something.
- Previously, the original link element was not removed, but they are just made invisible by setting `style.display = "none"`. But now, the text content of the original link element is actually removed. If this breaks things, let me know.

**Comment by zhaoshenzhai** [comment]
Hi @RyotaUshio. Very cool! Thanks again for your contributions. I must admit my previous implementation was very rough, so thanks for fixing it.

I went over your changes briefly, and the only thing that I would change is to replace my `addMathLink` with your new `renderTextWithMath`; your's is much cleaner! Having it as `async` does cause some issues if I were to use it in live-preview too, and removing the `async` causes some issues with dataview inline fields (which is what

> * Now, there is no `mathLink-internal-link`/`original-internal-link` classes in the reading mode. I think they are no more needed under the current implementation, but let me know if I'm missing something.

those classes are for). I will look into it tonight after finishing up some school work :)

**Comment by zhaoshenzhai** [comment]
> I think now the API is mature enough to be released. If you are fine with it, could you merge this PR and publish it to the npm registry?
> 
> Also, I appreciate it if you could include this in the next release so that the users of my plugin can enjoy the new features. (Of course, I don't mean to rush you if you have something that you want to include in it other than this API update.)

I will release it tonight

**Comment by zhaoshenzhai** [comment]
I do not have a nice solution for the dataview inline fields under this new implementation (admitedly, I do not know why it even needs special attention...), but for now adding a synchronous version of `renderTextWithMath` seems to work.

**Comment by RyotaUshio** [comment]
Thank you so much for the prompt response!
Also, I'm pleased to hear the dataview issue has been successfully resolved. (I don't have a clear explanation for the problem either, but I'll let you know if I find something)

Once again,  I truly appreciate the entire collaboration process! It will enhance the experience for many people in the near future :)

**Pull request merged**
