### PR TITLE
Fix issue 41

### PR DESCRIPTION
**Pull request by RyotaUshio**
Added some logging code.

### CODE REVIEW

**Comment by RyotaUshio** [comment]
It looks like the key challenge is differentiating `[note](note.md)` from `[Obsidian](https://obsidian.md/)`...
`

**Comment by RyotaUshio** [comment]
Some minor comments:

- You can check the current mode (reading view/editing view, live preview/source mode) without using anything not exposed in the API. See https://github.com/RyotaUshio/obsidian-math-booster/blob/a7fc24ea6abe0e13e15957b01f20472bcb38ff58/src/utils.ts#L226-L240
- You can use [view.state.selection.main](https://codemirror.net/docs/ref/#state.EditorSelection.main) instead of `view.state.selection.ranges[0]`.
- `destroyDecorations` seems to be just iterating nodes without doing anything. How about just returning [Decoration.none](https://codemirror.net/docs/ref/#view.Decoration^none)?

**Comment by RyotaUshio** [comment]
Now I see the problem...

image

**Comment by RyotaUshio** [comment]
I don't know why, but the following doesn't work.

```ts
            mathLinkWrapper.onclick = (async (evt: MouseEvent) => {
                evt.preventDefault();
                try {
                    await plugin.app.workspace.openLinkText(this.outLinkText, outLinkFileName, evt.ctrlKey || evt.metaKey);
                } catch (err) {
                    location.href = this.outLinkText;
                }
            });

```

**Comment by RyotaUshio** [comment]
This doesn't work either:

```ts
            mathLinkWrapper.onclick = (async (evt: MouseEvent) => {
                evt.preventDefault();
                try {
                    await plugin.app.workspace.openLinkText(this.outLinkText, outLinkFileName, evt.ctrlKey || evt.metaKey);
                } catch (err) {
                    self.open(this.outLinkText, "_blank", "noreferrer")
                }
            });
```

**Comment by RyotaUshio** [comment]
I mean, the `try .. catch ...` syntax doesn't work. The error is still thrown.

**Comment by RyotaUshio** [comment]
This is not directly related to issue #41, but I noticed that the second argument `sourcePath` of `openLinkText` is improper.

According to the [doc](https://docs.obsidian.md/Reference/TypeScript+API/FileManager/generateMarkdownLink), `sourcePath` is "where the link is stored in, used to compute relative links."

But here, the "target path" is passed as `sourcePath`.

**Comment by RyotaUshio** [comment]
Finally managed to fix it! Let me know if something is wrong.

**Comment by zhaoshenzhai** [comment]
Hi! This mostly works, except when links to a section heading (or an id) is clicked, it does not open the note at the appropriate place.

**Comment by RyotaUshio** [comment]
I was totally missing that point...

In my last commit, I used `getLeaf` & `openFile` instead of `openLinkText` because we've already done the step of parsing link text and I wanted to avoid repeating the same process. 
But if it's not a big problem, we can just replace
```ts
plugin.app.workspace.getLeaf(Keymap.isModEvent(evt)).openFile(targetFile);
```
with 
```ts
plugin.app.workspace.openLinkText(this.outLinkText, sourcePath, Keymap.isModEvent(evt));
```

**Comment by zhaoshenzhai** [comment]
Oh okay! I thought that line was the one causing problems... I will replace it and test some more (might do it tomorrow though)

**Comment by RyotaUshio** [comment]
By the way, thanks for the quick response as always!

**Comment by zhaoshenzhai** [comment]
> The problem was not `openLinkText` itself, but passing it `this.openLinkText` that is not a proper internal link text (i.e. an internal link to an existing file in the vault). For example, "https://..." and "obsidian://..." are not.
> 
> So, it's totally fine as long as the first argument of `openLinkText` is guaranteed to be a proper internal link by the following `if` statement:

ahhh yes I understand now. Thanks! I tested your example and it works, so I'll merge it now.

**Pull request merged**
