### PR TITLE
Fix issue 42

### PR DESCRIPTION
**Pull request by RyotaUshio**
#42 

Added some logging code for debugging.

### CODE REVIEW

**Comment by RyotaUshio** [comment]
Maybe it's fixed. Let me know if this change causes another issue.

## Reading view 

image

## Live preview

image

**Comment by zhaoshenzhai** [comment]
I made a minor change to account for links like `[Main](Main.md)` where Main.md has `mathLink: $\alpha$`, but kept the rest unchanged.

Scrot_2023_08_25_113814

**Comment by RyotaUshio** [comment]
Do you mean the link on the left side should be rendered as $\mathcal{N}$ ote?  I've pulled your latest commit but it doesn't work...

image

**Comment by zhaoshenzhai** [comment]
In your example, I think `[note](note.md)` should render as $\mathcal{N}ote$, while `[foo](note.md)` should render as just `foo`.

**Comment by RyotaUshio** [comment]
Oh I see, then it perfectly works!

**Comment by RyotaUshio** [comment]
@zhaoshenzhai A minor point, but this line needs to be optional chaining `?.` since `targetEl.getAttribute("data-href")` might be `null`.

https://github.com/zhaoshenzhai/obsidian-mathlinks/blob/053ce4ce758821bf556d9ca11c4f293be45250b0/src/links/reading.ts#L85

that is

```ts
targetEl.getAttribute("data-href")?.replace(/\.md/, ""); 
```

**Comment by zhaoshenzhai** [comment]
Right, yes, thank you!

**Pull request merged**
